---
- name: ADD BEAKER_HOST
  hosts: localhost
  tasks:
    - block:
        - name: Add hostRequires.fqdn to beaker-host group
          add_host:
            hostname: "{{ hostRequires.fqdn }}"
            ansible_ssh_host: "{{ hostRequires.fqdn }}"
            ansible_ssh_port: "{{ beaker_host_port | default('22') }}"
            ansible_user: "{{ beaker_host_user | default('root') }}"
            ansible_password: "{{ beaker_host_password | default('beaker') }}"
            groups:
              - beaker-host
      rescue:
        - include_tasks: dci/failure.yml
      when: hostRequires.fqdn is defined

- name: PREPARE LAB
  hosts: beaker-lab
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - include_tasks: dci/import.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
      - prepare_lab

- name: LAUNCH INSTALL
  hosts: localhost
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: dci/install.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
      - install

- name: TESTS
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - name: Launch RHEL Certification Test
          import_role:
            name: dci-rhel-certification
          when:
            - topic.startswith('RHEL-7')|bool
            - dci_rhel_agent_cert|bool
          become: true
      rescue:
        - include_tasks: dci/release.yml
        - include_tasks: dci/failure.yml
  tags:
      - test

- name: 'Launch customizable tests'
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: '{{ dci_config_dir }}/hooks/user-tests.yml'
      rescue:
        - include_tasks: dci/failure.yml
  tags:
    - post-run

- name: RELEASE SERVER
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: dci/release.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
    - post-run

- name: SUCCESS
  hosts: localhost
  vars:
    dci_status: 'success'
  tasks:
    - include_tasks: dci/success.yml
  tags:
      - success
