---
- name: NEW JOB
  hosts: localhost
  tasks:
    - name: schedule a new job
      dci_job:
        components: '{{ dci_components }}'
        topic: '{{ topic }}'
      register: job_info

    - name: set global variables
      set_fact:
        job_id: "{{ job_info['job']['id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        remoteci_id: "{{ job_info['job']['remoteci_id'] }}"
        components: "{{ job_info['job']['components'] }}"
        product: "{{ job_info['job']['topic']['product_id'] }}"

    - name: Set the tags
      dci_job:
        id: "{{ job_id }}"
        tags: '{{ dci_tags }}'
      when: dci_tags

    - include_tasks: hooks/clean.yml
  tags:
      - new_job


- name: Retrieve keys and components
  hosts: localhost
  tasks:
    - block:
        - include_tasks: dci/prepare.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
    - new_job


- name: PREPARE LAB
  hosts: beaker-lab
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - include_tasks: hooks/import.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
      - prepare_lab

- name: LAUNCH INSTALL
  hosts: localhost
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: hooks/install.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
      - install

- name: TESTS
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - name: Launch RHEL Certification Test
          import_role:
            name: dci-rhel-certification
          when: dci_rhel_agent_cert|bool
          become: true
      rescue:
        - include_tasks: dci/release.yml
        - include_tasks: dci/failure.yml
  tags:
      - test

- name: 'Launch customizable tests'
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: '{{ dci_config_dir }}/hooks/user-tests.yml'
      rescue:
        - include_tasks: dci/failure.yml
  tags:
    - post-run

- name: RELEASE SERVER
  hosts: beaker-host
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: dci/release.yml
      rescue:
        - include_tasks: dci/failure.yml
  tags:
    - post-run

- name: SUCCESS
  hosts: localhost
  vars:
    dci_status: 'success'
  tasks:
    - include_tasks: dci/success.yml
  tags:
      - success
