- hosts: testrunner
  tasks:
    - name: Start docker daemon
      service:
        name: docker
        state: started
      become: true

    - name: "Login to {{ registry }} registry"
      shell: "docker login --username=\"{{ username }}\" --password=\"{{ password }}\" {{ registry }}"
      become: true

    - name: "list available images"
      shell: "docker images"
      become: true

    - name: "Push {{ tag }} image on {{ registry }}"
      shell: "docker push {{ registry }}/{{ tag }}"
      become: true