# This is for backwards compatabilty

- name: Setup vlan interface
  when:
    - bridge_interface is defined
    - vlan_tag is defined
  block:
    - name: Build vlan interface definition
      set_fact:
        vlan_interface:
          name: "{{ vlan_name }}"
          type: vlan
          vlan:
            interface: "{{ bridge_interface }}"
            tag: "{{ vlan_tag }}"

    - name: Set bridge_port_name as vlan interface name
      set_fact:
        bridge_port_name: "{{ vlan_name }}"

- name: Build bridge interface definition and add to interfaces list
  set_fact:
    network_config_interfaces:
      - type: linux-bridge
        name: "{{ bridge_name }}"
        addresses:
          ipv4:
            - ip: "{{ bridge_ip }}"
              prefix: "{{ bridge_prefix }}"
        bridge:
          stp: True
          port:
            name: "{{ bridge_port_name }}"
  when: bridge_interface is defined

- name: Build bridge interface definition and add to interfaces list
  set_fact:
    network_config_interfaces:
      - type: linux-bridge
        name: "{{ bridge_name }}"
        addresses:
          ipv4:
            - ip: "{{ bridge_ip }}"
              prefix: "{{ bridge_prefix }}"
        bridge:
          stp: True
  when: bridge_interface is not defined

- name: Append vlan to network_config_interfaces
  set_fact:
    network_config_interfaces: "{{ network_config_interfaces + [vlan_interface] }}"
  when: vlan_tag is defined

- name: Build network_config
  set_fact:
    network_config:
      interfaces: "{{ network_config_interfaces }}"
