---
- name: Setup virt host
  gather_facts: true
  gather_subset:
    - '!all'
    - user_id
  hosts:
    - localhost
  tags:
    - bootstrap_libvirt
  tasks:
    - name: Destroy vms
      include_role:
        name: destroy_vms

    - name: Setup VM host network
      include_role:
        name: setup_vm_host_network

    - name: Setup VM host software
      include_role:
        name: setup_vm_host_software

    - name: Create vms
      include_role:
        name: create_vms

    - name: Setup Virtual BMC
      include_role:
        name: setup_virtual_bmc

- name: Apply role jumpbox
  gather_facts: true
  gather_subset:
    - '!all'
    - '!min'
    - network
    - user_id
  hosts:
    - localhost
  tags:
    - dci_setup
  roles:
    - role: dci_setup
