---
- name: Firewall Enabled
  block:
    - name: Install firewalld Packages
      package:
        name:
          - firewalld
        state: present

    - name: Manage firewalld service
      systemd:
        name: firewalld
        state: "started"
        enabled: "true"

    - name: Open tcp ports via firewalld
      ansible.posix.firewalld:
        port: "{{ item[0] }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
        zone: "{{ item[1] }}"
      loop: "{{ tcp_ports | product(firewall_zones) | list }}"

    - name: Open udp ports via firewalld
      ansible.posix.firewalld:
        port: "{{ item[0] }}/udp"
        permanent: yes
        immediate: yes
        state: enabled
        zone: "{{ item[1] }}"
      loop: "{{ udp_ports | product(firewall_zones) | list }}"

    # Restart the pods if we enabled the firewalld
    - name: Restart Pods
      systemd:
        name: "{{ item }}"
        state: "restarted"
        enabled: "true"
      loop:
        - "http_store"
        - "beaker"

  when: firewall_enabled
...
