---
- name: Configure conserver
  hosts: jumpbox
  become: yes
  gather_facts: no
  tags: conserver
  tasks:
    - name: Install required packages
      package:
        name:
          - conserver
          - conserver-client
        state: present
    - name: Create /var/consoles if it does not exist
      file:
        path: /var/consoles
        state: directory
        mode: '0755'
    - name: Create conserver.cf file
      template:
        src: conserver.cf.j2
        dest: /etc/conserver.cf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart conserver
  handlers:
    - name: restart conserver
      service:
        name: conserver
        state: restarted
