---
- name: PREPARE LAB
  hosts: beaker_server
  gather_facts: no
  tasks:
    - block:
        - name: Start dci-downloader
          shell: hostname -a
          become: true
        - name: Import the latest build
          shell: beaker-import -v --ignore-missing-tree-compose "http://{{ local_repo_ip }}/{{ topic }}/compose/"
          become: true
      rescue:
        - include_tasks: failure.yml
