---
- name: PREPARE LAB
  hosts: beaker-lab
  vars:
    dci_status: 'pre-run'
    topic_url:
      RHEL-7:   'http://{{ local_repo_ip }}/{{ topic }}/'
      RHEL-7.6: 'http://{{ local_repo_ip }}/{{ topic }}/'
      RHEL-7.7: 'http://{{ local_repo_ip }}/{{ topic }}/'
      RHEL-8:   'http://{{ local_repo_ip }}/{{ topic }}/'
      RHEL-8.0: 'http://{{ local_repo_ip }}/{{ topic }}/compose/'
      RHEL-8.1: 'http://{{ local_repo_ip }}/{{ topic }}/compose/'
  tasks:
    - block:
        - name: Import the latest build
          shell: beaker-import -v --ignore-missing-tree-compose {{ topic_url[topic] }}
      rescue:
        - include_tasks: failure.yml
  tags:
      - prepare_lab
