---
- name: Cleanup boot files on Beaker server copied by agent
  hosts: beaker_server
  gather_facts: false
  tasks:
    - name: Remove bootx and grubx files copied by agent
      file:
        path: "/var/lib/tftpboot/{{ item }}"
        state: absent
      with_items:
        - BOOTX64.EFI
        - grubx64.efi
        - BOOTAA64.EFI
        - grubaa64.efi

    - name: Remove ppc64le directories and files copied by agent
      shell: rm -Rf /var/lib/tftpboot/boot/grub2/*
      args:
        warn: no
