---
- name: NEW JOB
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read credentials
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

    - name: Schedule a new job
      dci_job:
        components: '{{ dci_components }}'
        topic: '{{ topic }}'
      register: job_info

    - name: Set global variables
      set_fact:
        job_id: "{{ job_info['job']['id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        remoteci_id: "{{ job_info['job']['remoteci_id'] }}"
        components: "{{ job_info['job']['components'] }}"
        product: "{{ job_info['job']['topic']['product_id'] }}"

    - name: Set the tags
      dci_job:
        id: "{{ job_id }}"
        tags: '{{ dci_tags }}'
      when: dci_tags
  tags:
      - new_job

- name: GENERATE SSH CONFIG FOR SUT
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        var: hostvars['beaker_server']  
    - block:
        - name: Create ssh config file for SUT
          template:
            src: /usr/share/dci-rhel-agent/templates/ssh_config.conf.j2
            dest: "/etc/dci-rhel-agent/secrets/ssh_config_{{ fqdn }}.cfg"
        - name: Upload ssh config to DCI
          dci_file:
            path: "/etc/dci-rhel-agent/secrets/ssh_config_{{ fqdn }}.cfg"
            name: 'ssh_config_sut.txt'
            mime: 'text/plain'
            job_id: '{{ hostvars.localhost.job_id }}'
      rescue:
      - include_tasks: failure.yml
      when:
        - fqdn is defined
        - hostvars['beaker_server']['ansible_host'] != "local"

- name: ADD BEAKER_SUT
  hosts: localhost
  vars:
    topic_interpreter:
      RHEL-7:   'python'
      RHEL-7.6: 'python'
      RHEL-7.7: 'python'
      RHEL-7.8: 'python'
      RHEL-8:   '/usr/libexec/platform-python'
      RHEL-8.0: '/usr/libexec/platform-python'
      RHEL-8.1: '/usr/libexec/platform-python'
      RHEL-8.2: '/usr/libexec/platform-python'
  tasks:
    - block:
        - name: Add SUT to the Ansible group
          add_host:
            hostname: "{{ fqdn }}"
            ansible_python_interpreter: "{{ topic_interpreter[topic] }}"
            ansible_ssh_host: "{{ fqdn }}"
            ansible_ssh_port: "{{ beaker_sut_port | default('22') }}"
            ansible_user: "{{ beaker_sut_user | default('root') }}"
            ansible_password: "{{ beaker_sut_password | default('beaker') }}"
            ansible_ssh_common_args: "-F /etc/dci-rhel-agent/secrets/ssh_config_{{ fqdn }}.cfg"
            groups:
              - beaker_sut
      rescue:
        - include_tasks: failure.yml
      when: fqdn is defined

- name: GET SUT ARCH
  hosts: beaker_server
  gather_facts: no
  tasks:
    - block:
        - name: Get SUT details
          shell: "bkr system-details {{ fqdn }}"
          register: system_details
          become: true

        - name: Parse arch from SUT details
          xml:
            xmlstring: "{{ system_details.stdout }}"
            xpath: inv:System/inv:supportsArch/inv:Arch/rdfs:label
            namespaces:
              inv: https://fedorahosted.org/beaker/rdfschema/inventory#
              rdfs: http://www.w3.org/2000/01/rdf-schema#
            content: text
          register: supported_arch_info

        - name: Register supported arch
          set_fact:
            system_arch: "{{ supported_arch_info.matches[0].values().pop() }}"
      rescue:
         - include_tasks: failure.yml
      when: fqdn is defined

- name: LAUNCH INSTALL
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: create_temp_dir.yml
        - include_tasks: install.yml
      # rescue:
      #   - include_tasks: failure.yml
  tags:
      - install

# - name: TESTS
#   hosts: beaker_sut
#   vars:
#     dci_status: 'post-run'
#   tasks:
#     - block:
#         - name: Launch RHEL Certification Test
#           import_role:
#             name: dci-rhel-certification
#           when:
#             - topic.startswith('RHEL-7')|bool
#             - dci_rhel_agent_cert|bool
#           become: true
#       rescue:
#         - include_tasks: release.yml
#         - include_tasks: failure.yml
#   tags:
#       - test

- name: 'Launch customizable tests'
  hosts: beaker_sut
  vars:
    dci_status: 'post-run'
  tasks:  
    - block:
        - include_tasks: '{{ dci_config_dir }}/hooks/user-tests.yml'
      rescue:
        - name: Fail properly
          fail:
            msg: 'Something went wrong during the {{ dci_status }}. Review the log at: https://www.distributed-ci.io/jobs/{{ hostvars.localhost.job_info.job.id }}/jobStates'
  tags:
    - post-run

- name: RELEASE SERVER
  hosts: beaker_server
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: release.yml
      rescue:
        - include_tasks: failure.yml
  tags:
    - post-run

- name: SUCCESS
  hosts: localhost
  vars:
    dci_status: 'success'
  tasks:
    - include_tasks: success.yml
  tags:
      - success

