---
- name: PREPARE LAB
  hosts: beaker-lab
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - name: Import the latest build
          shell: beaker-import -v --ignore-missing-tree-compose "http://{{ local_repo_ip }}/{{ topic }}/compose/"
      rescue:
        - include_tasks: failure.yml
  tags:
      - prepare_lab
