---
- name: NEW JOB
  hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Read credentials from env vars'
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

    - name: 'Schedule a new job in DCI Control Server'
      dci_job:
        components: '{{ dci_components }}'
        topic: '{{ topic }}'
      register: job_info

    - name: 'Set global variables'
      set_fact:
        job_id: "{{ job_info['job']['id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        remoteci_id: "{{ job_info['job']['remoteci_id'] }}"
        components: "{{ job_info['job']['components'] }}"
        product: "{{ job_info['job']['topic']['product_id'] }}"

    - name: 'Set DCI tags for the current job'
      dci_job:
        id: "{{ job_id }}"
        tags: '{{ dci_tags }}'
      when: dci_tags

- name: 'Configure SUT'
  hosts: localhost
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: sut.yml
      rescue:
        - include_tasks: failure.yml

- name: 'Prepare install'
  hosts:
    - localhost
    - beaker_server
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: create_temp_dir.yml
      rescue:
        - include_tasks: failure.yml

- name: Install RHEL on SUT
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: install.yml
      rescue:
        - include_tasks: failure.yml

- name: 'Upload Beaker logs to DCI Control server'
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: logs.yml
      rescue:
        - include_tasks: failure.yml

- name: 'Launch customizable tests'
  hosts: beaker_sut
  gather_facts: no
  vars:
    dci_status: 'post-run'
  tasks:
    - include_tasks: '{{ dci_config_dir }}/hooks/user-tests.yml'

- name: 'Release SUT in Beaker'
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: release.yml
      rescue:
        - include_tasks: failure.yml

- name: SUCCESS
  hosts: localhost
  gather_facts: no
  vars:
    dci_status: 'success'
  tasks:
    - include_tasks: success.yml