---
- name: Prepare import
  hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Read credentials from env vars'
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

- name: Download and import RHEL in Beaker
  hosts: beaker_server
  gather_facts: no
  tasks:
    - name: Create a temporary file
      tempfile:
        state: file
        prefix: "dci_"
        suffix: _settings.yml
      register: setting_yml
      when: hostvars.beaker_server['ansible_connection'] is not defined

    - name: Upload settings.yml to Beaker server
      copy:
        src: '/etc/dci-rhel-agent/settings.yml'
        dest: "{{ setting_yml.path }}"
        mode: '0755'
      when: hostvars.beaker_server['ansible_connection'] is not defined

    - name: Configure settings path
      set_fact:
        dci_config_file: "{{ setting_yml.path }}"
      when: hostvars.beaker_server['ansible_connection'] is not defined

    - name: Start dci-downloader
      environment:
        - DCI_CLIENT_ID: "{{ hostvars.localhost.dci_client_id }}"
        - DCI_API_SECRET: "{{ hostvars.localhost.dci_api_secret }}"
        - DCI_CS_URL: "{{ hostvars.localhost.dci_cs_url }}"
      shell: /bin/dci-downloader --settings {{ dci_config_file }}
      become: true

    - name: Import the latest build
      shell: beaker-import -v --ignore-missing-tree-compose "http://{{ local_repo_ip }}/{{ topic }}/compose/"
      become: true

    - name: Delete the temporary file
      file:
        path: "{{ setting_yml.path }}"
        state: absent
      when: hostvars.beaker_server['ansible_connection'] is not defined