---
- name: NEW JOB
  hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Read credentials from env vars'
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

    - name: 'Schedule a new job in DCI Control Server'
      dci_job:
        components: '{{ dci_components }}'
        topic: '{{ topic }}'
      register: job_info

    - name: 'debug dci_job_id'
      debug:
        msg: dci_job_id:"{{ job_info['job']['id'] }}"

    - name: 'Set global variables'
      set_fact:
        job_id: "{{ job_info['job']['id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        remoteci_id: "{{ job_info['job']['remoteci_id'] }}"
        components: "{{ job_info['job']['components'] }}"
        product: "{{ job_info['job']['topic']['product_id'] }}"

    - name: 'Set DCI tags for the current job'
      dci_job:
        id: "{{ job_id }}"
        tags: '{{ dci_tags }}'
      when: dci_tags | length > 0

- name: Upload settings and hooks
  hosts: localhost
  environment:
    - DCI_CLIENT_ID: "{{ hostvars.localhost.dci_client_id }}"
    - DCI_API_SECRET: "{{ hostvars.localhost.dci_api_secret }}"
    - DCI_CS_URL: "{{ hostvars.localhost.dci_cs_url }}"
  tasks:
    - name: Upload settings yml file
      ignore_errors: yes
      dci_file:
        path: /etc/dci-rhel-agent/settings.yml
        name: settings.yml
        job_id: "{{ hostvars.localhost.job_id }}"
    - name: Upload hooks directory contents
      dci_file:
        path: "{{ item }}"
        name: "{{ item | basename }}"
        job_id: "{{ hostvars.localhost.job_id }}"
      with_fileglob:
        - /etc/dci-rhel-agent/hooks/*

- name: 'Download topic'
  hosts: localhost
  gather_facts: no
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - include_tasks: dci-import.yml
      rescue:
        - include_tasks: failure.yml
      when: not hostvars.localhost.tests_only

- name: 'Configure SUT'
  hosts: localhost
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: sut.yml
      rescue:
        - include_tasks: failure.yml

- name: 'Prepare install'
  hosts:
    - localhost
    - beaker_server
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: create_temp_dir.yml
      rescue:
        - include_tasks: failure.yml

- name: 'Launch pre-run'
  hosts: localhost
  tags:
    - pre-run
  vars:
    dci_status: 'pre-run'
  tasks:
    - block:
        - stat:
            path: '/etc/dci-rhel-agent/hooks/pre-run.yml'
          register: check_pre_run
        - stat:
            path: '/etc/dci-rhel-agent/hooks/user-tests.yml'
          register: check_user_tests
        - name: Run the pre-run hook
          include_tasks: '/etc/dci-rhel-agent/hooks/pre-run.yml'
          when: check_pre_run.stat.exists
      rescue:
        - include_tasks: failure.yml

- name: Install RHEL on SUT
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'running'
  tasks:
    - block:
        - include_tasks: install.yml
      rescue:
        - include_tasks: logs.yml
        - include_tasks: release.yml
        - include_tasks: failure.yml
      when: not hostvars.localhost.tests_only

- name: 'Launch customizable tests'
  hosts: beaker_sut
  gather_facts: yes
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: '/etc/dci-rhel-agent/hooks/user-tests.yml'
          when: hostvars.localhost['check_user_tests'].stat.exists
      rescue:
        - include_tasks: release.yml
        - include_tasks: failure.yml

- name: Red Hat Tests
  hosts: beaker_sut
  vars:
    dci_status: 'post-run'
  tasks:
    - name: Launch RHEL CKI Test
      ignore_errors: yes
      import_role:
        name: dci-rhel-cki
      when:
        - dci_rhel_agent_cki|bool
      become: true

    - name: Launch RHEL HW Cert Tests
      ignore_errors: yes
      import_role:
        name: dci-rhel-certification
      when:
        - dci_rhel_agent_cert|bool
      become: true
  tags:
      - test

- name: 'Upload Beaker logs to DCI Control server'
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: logs.yml
      rescue:
        - include_tasks: release.yml
        - include_tasks: failure.yml

- name: 'Release SUT in Beaker'
  hosts: beaker_server
  gather_facts: no
  vars:
    dci_status: 'post-run'
  tasks:
    - block:
        - include_tasks: release.yml
      rescue:
        - include_tasks: failure.yml

- name: SUCCESS
  hosts: localhost
  gather_facts: no
  vars:
    dci_status: 'success'
  tasks:
    - block:
        - include_tasks: success.yml
      rescue:
        - include_tasks: failure.yml
