vm_bridge_ip: "{{ machine_network_cidr | ipaddr('next_usable') }}"
vm_bridge_prefix: "{{ machine_network_cidr | ipaddr('prefix') }}"
vm_bridge_name: "dci-br"
vm_bridge_port_name: "{{ vm_bridge_interface }}"
vm_vlan_name: "dci.100"
vm_nmstate_config_path: "/tmp/dci_nmstate.yml"
