---
- name: Update all packages on the system
  become: true
  yum:
    name: "*"
    state: latest

- name: Install epel-release
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Exclude nodejs and npm from epel (temp)
  become: true
  shell:
    yum-config-manager --save --setopt=epel.exclude=nodejs*,npm

- name: Install DCI-release
  become: true
  yum:
    name: "http://packages.distributed-ci.io/dci-release.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install needed packages
  become: true
  yum:
    name:
      - dci-rhel-agent
      - ansible
      - git
      - wget
    state: present

- name: Create the dci-rhel-agent user
  become: true
  user:
    name: dci-rhel-agent
    comment: dci-rhel-agent user
    group: wheel

- name: Add NOPASSWD for the user dci-rhel-agent
  become: true
  lineinfile:
    path: /etc/sudoers.d/dci_rhel_agent
    state: present
    regexp: '^dci-rhel-agent ALL='
    line: 'dci-rhel-agent ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
    create: yes

- name: Git clone
  become: true
  become_user: dci-rhel-agent
  git:
    repo: https://github.com/redhat-cip/ansible-playbook-dci-beaker
    dest: /home/dci-rhel-agent/ansible-playbook-dci-beaker
    force: yes

- name: Install beaker requierements
  become: true
  become_user: dci-rhel-agent
  shell: ansible-galaxy install -r requirements.yml -p roles/
  args:
    chdir: ~dci-rhel-agent/ansible-playbook-dci-beaker/

- name: Ensure beaker in the inventory use local connection
  become: true
  become_user: dci-rhel-agent
  lineinfile:
    path: /home/dci-rhel-agent/ansible-playbook-dci-beaker/inventory
    regexp: '^beaker ansible_host=<hostname> ansible_user=<user>'
    insertafter: '^#beaker '
    line: beaker ansible_connection=local

- name: Install beaker
  become: true
  become_user: dci-rhel-agent
  shell: ansible-playbook -i inventory playbook.yml -e "rhsm_autosubscribe=false role_redhat_subscription=false" --skip-tags=firewall
  args:
    chdir: ~dci-rhel-agent/ansible-playbook-dci-beaker/

- name: Install beaker Harness
  become: true
  shell:
    beaker-repo-update
  args:
    chdir: /var/www/beaker

- name: Add port in the IPMI beaker script
  become: true
  replace:
    path: /etc/beaker/power-scripts/ipmitool_lanplus
    regexp: '(.*)\$power_pass" power(.*)'
    replace: '\1$power_pass" -p 6230 -N 60 power\2'

- name: Generate a key for dci_rhel_agent
  become: true
  community.crypto.openssh_keypair:
    path: /etc/dci-rhel-agent/secrets/id_rsa
  register: dci_rhel_agent_key

- name: Add dci_rhel_agent key to authorized key
  become: true
  authorized_key:
    user: root
    state: present
    key: "{{ dci_rhel_agent_key.public_key }}"

- name: Git clone
  become: true
  become_user: dci
  git:
    repo: https://softwarefactory-project.io/r/dci-rhel-agent
    dest: /home/dci/dci-rhel-agent
    force: yes
